### ISSUE TITLE
Problem with password recovery link

### ISSUE THREAD

**Issue by ManuelNeto280690** [designatedcoder/coders_conduct#1]
I'm having a problem with password recovery, I get the link in the email, but the reset password button redirects to a laravel recovery page, although I disabled the views in fortify, it shows http://localhost:8000/reset -password/7a07d95a18d2e4de2f3acb13fe1ff042a5acf0753ce15b87f12f2f3179a6fc7d?email=webangola connection%40gmail.com

**Comment by designatedcoder** [comment]
If that's the link you're getting I think you missed a couple of steps.  Check your code again and let me know so that I can close this as an issues.
